# Generated by Django 3.2 on 2021-04-28 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=120)),
                ('level', models.PositiveIntegerField()),
                ('date_admitted', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField()),
                ('reg_no', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
    ]
